FROM golang

RUN ["go", "get", "github.com/codegangsta/gin"]

VOLUME ["/go/src/github.com/tobyjsullivan/ues-projection-svc"]

EXPOSE 3000

WORKDIR /go/src/github.com/tobyjsullivan/ues-projection-svc

CMD ["gin"]

