version: '3'
services:
  ues-projection-svc:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
    - .:/go/src/github.com/tobyjsullivan/ues-projection-svc
    ports:
    - "6400:3000"
    depends_on:
    - "event-log"
    - "event-log-reader"
    environment:
    - SERVICE_LOG_ID=fbd8aab2-06ad-4738-84d8-1156adae860e
    - LOG_READER_API=http://event-log-reader:3000/
  ues-command-api:
    image: tobyjsullivan/ues-command-api:1.0
    ports:
    - "6404:3000"
    depends_on:
    - "event-log"
    - "event-log-reader"
    environment:
    - SERVICE_LOG_ID=fbd8aab2-06ad-4738-84d8-1156adae860e
    - LOG_WRITER_API=http://event-log:3000/
    - LOG_READER_API=http://event-log-reader:3000/
  event-log-reader:
    image: tobyjsullivan/event-log-reader:1.1
    ports:
    - "6405:3000"
    depends_on:
    - "log-db"
    - "event-reader"
    environment:
    - EVENT_READER_API=http://event-reader:3000/
    - PG_HOSTNAME=log-db
    - PG_USERNAME=postgres
    - PG_PASSWORD=pass1234
    - PG_DATABASE=postgres
    - REDIS_HOSTNAME=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=
  redis:
    image: redis:3.0
    volumes:
    - ./data/redis:/data
  event-log:
    image: tobyjsullivan/event-log:1.1
    ports:
    - "6401:3000"
    depends_on:
    - "log-db"
    - "event-store"
    environment:
    - EVENT_STORE_API=http://event-store:3000/
    - PG_HOSTNAME=log-db
    - PG_USERNAME=postgres
    - PG_PASSWORD=pass1234
    - PG_DATABASE=postgres
  log-db:
    image: tobyjsullivan/logs-db:1.0
    environment:
    - POSTGRES_PASSWORD=pass1234
    volumes:
    - ./data/log:/var/lib/postgresql/data
  event-reader:
    image: tobyjsullivan/event-reader:3.0
    env_file:
    - ./env/event-reader.env
  event-store:
    image: tobyjsullivan/event-store:3.0
    env_file:
    - ./env/event-store.env

